### PR TITLE
Closes #199 Fixing Dark Mode on Feed Screen

### LINKED ISSUE #199: Dark Mode Feed Screen
When you switch to dark mode launch app and open Feed bottom navigation destination, the text is not visible. The dark mode designs can be found [here](https://xd.adobe.com/view/5ec235b6-c3c6-49a9-b783-1f1303deb1a8-0b91/screen/6542ef9c-83d3-4620-be14-dbd5f31c7464/)

image

### PR DESCRIPTION
**Pull request by AmenyaZ**
# Scope

_Please make sure to read the [Contribution Guidelines](https://github.com/droidconKE/droidconKE2023Android/blob/main/CONTRIBUTING.md)
and check that you understand and have followed it as best as possible Explain what your feature
does in a short paragraph._ please check the below boxes
- [x] I have followed the coding conventions
- [x] I have added/updated necessary tests
- [x] I have tested the changes added on a physical device
- [x] I have run `./codeAnalysis.sh` on linux/unix or `codeAnalysys.bat` on windows to make sure all lint/formatting checks have been done.

## Closes/Fixes Issues
_Declare any issues by typing `fixes #1` or `closes #1` for example so that the automation can kick
in when this is merged_

## Other testing QA Notes
_What have you tested specifically and what possible impacts/areas there are that may need retesting
by others._

Please add a screenshot (if necessary)

### CODE REVIEW

File: presentation/src/main/java/com/android254/presentation/feed/view/FeedComponent.kt [hunk 1]
```diff
@@ -60,11 +60,15 @@ fun FeedComponent(
...
+            .padding(horizontal = 15.dp, vertical = 2.dp)
             .wrapContentHeight(),
-        shape = RoundedCornerShape(0.dp),
-        colors = CardDefaults.cardColors(
-            containerColor = ChaiLightGrey
-        )
+//        shape = RoundedCornerShape(0.dp),
+//        colors = CardDefaults.cardColors(
+//            containerColor = ChaiLightGrey
+//        )
```
Comment (chepsi) [inline presentation/src/main/java/com/android254/presentation/feed/view/FeedComponent.kt:68]: unnecessary comment here.

**Comment by chepsi** [comment]
@AmenyaZ do you mind adding a screenshot?

**Comment by AmenyaZ** [comment]
> @AmenyaZ do you mind adding a screenshot?
Screenshot_20231012-101927_DroidconKE2023

**Review by chepsi — APPROVED** [review]
